doctrine:
    orm:
        entity_managers:
            pimcore:
                connection: default
                mappings:
                    PimcoreJobExecutionEngineBundle:
                        type: attribute
                        is_bundle: true
                        dir: "src/Entity"
                        prefix: Pimcore\Bundle\JobExecutionEngineBundle\Entity
                        alias: PimcoreJobExecutionEngineBundle