services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    _instanceof:
        # all services implementing the JobExecutionEngineMessageInterface
        # will be registered on the bus
        Pimcore\Bundle\JobExecutionEngineBundle\Messenger\Messages\JobExecutionEngineMessageInterface:
            tags:
                - { name: messenger.message_handler, bus: job.execution.engine.bus }

    # ---------------------
    # INSTALLER
    # ---------------------
    Pimcore\Bundle\JobExecutionEngineBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('PimcoreJobExecutionEngineBundle')"


    # ---------------------
    # Job Execution Engine
    # ---------------------
    Pimcore\Bundle\JobExecutionEngineBundle\Agent\JobExecutionAgentInterface:
        class: Pimcore\Bundle\JobExecutionEngineBundle\Agent\JobExecutionAgent
        arguments:
            $environment: '%kernel.environment%'

    Pimcore\Bundle\JobExecutionEngineBundle\Repository\JobRunRepositoryInterface:
        class: Pimcore\Bundle\JobExecutionEngineBundle\Repository\JobRunRepository
        arguments:
            $pimcoreEntityManager: "@doctrine.orm.pimcore_entity_manager"

    Pimcore\Bundle\JobExecutionEngineBundle\Grid\JobRunGridInterface:
        class: Pimcore\Bundle\JobExecutionEngineBundle\Grid\JobRunGrid

    Pimcore\Bundle\JobExecutionEngineBundle\CurrentMessage\CurrentMessageProviderInterface:
        class: Pimcore\Bundle\JobExecutionEngineBundle\CurrentMessage\CurrentMessageProvider

    Pimcore\Bundle\JobExecutionEngineBundle\EventSubscriber\JobExecutionSubscriber: ~

    Pimcore\Bundle\JobExecutionEngineBundle\Messenger\Middleware\StepConditionMiddleware: ~

    Pimcore\Bundle\JobExecutionEngineBundle\Extractor\JobRunExtractorInterface:
        class: Pimcore\Bundle\JobExecutionEngineBundle\Extractor\JobRunExtractor

    # ---------------------
    # Security Services
    # ---------------------
    Pimcore\Bundle\JobExecutionEngineBundle\Security\PermissionServiceInterface:
        class: Pimcore\Bundle\JobExecutionEngineBundle\Security\PermissionService

    # ---------------------
    # Configuration
    # ---------------------
    Pimcore\Bundle\JobExecutionEngineBundle\Configuration\ExecutionContextInterface:
        class: Pimcore\Bundle\JobExecutionEngineBundle\Configuration\ExecutionContext

